openapi: 3.0.3
info:
  description: |-
    Each user will be presented with a stream of photos in reverse chronological order, with information
    about when it was uploaded (date and time) and how many likes and comments it has. Users can place
    (and later remove) a “like” to photos from other users. Also, users can add comments to any photo
    (even those uploaded by themself). Comments can be removed by the author only.

    Users can ban other users. If Alice (user) bans Eve (user), Eve won’t be able to see any information
    about Alice. Alice can decide to remove the ban at any moment.

    Users will have their own personal profiles. The personal profile page for user detail: user’s photos (in
    reverse chronological order), their followers and following, and how many photos have been uploaded.
    Each user can change his/her own username, upload photos, remove photos, and follow/unfollow
    other users. Removal of a photo will also remove likes and comments.

    Users profiles can be searched via username.

    The login is perfomed by specifying the username.
  title: WASAPhoto API
  version: 1.0.0
  contact:
    name: Lucian Dorin Crainic
    email: crainic.1938430@studenti.uniroma1.it
    url: https://github.com/LucianCrainic
  license:
    name: MIT
paths:
  /session/:
    #* doLogin
    post:
      tags: ["Login action"]
      summary: Logs in the user.
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content: 
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema: { $ref: "#/components/schemas/user"}
  /session/{Id}:
    parameters:
      - $ref : "#/components/parameters/Id"
    #* setMyUserName
    post: 
      tags: ["Session User actions"]
      summary: Sets user username.
      description: |-
        ## Information
        - If the **Id** provided exists then it sets a username for the profile.
        - If the **Id** provided does not exist then a 404 error response is given.
      operationId: setMyUserName
      requestBody:
        content:
          application/json:
            schema: {$ref: "#/components/schemas/user"}
      responses:
        "201":
          description: Username updated successfully.
        "404":
          description: User not found.
    #* getMyStream
    get:
      tags: ["Session User actions"]
      summary: Returns user Stream.
      operationId: getMyStream
      responses:
        "200": 
          description: OK
          content:
            image/*:
              schema: { $ref: "#/components/schemas/photo"}
        "400":
          description: User not found.
  /session/{Id}/{userId}: 
    parameters:
      - $ref: "#/components/parameters/Id"
      - $ref: "#/components/parameters/userId"
    #* getUserProfile
    get:
      tags: ["User actions"]
      summary: Returns user profile
      operationId: getUserProfile
      description: |-
        ## Information
        - If the **userId** provided by the **user(Id)** exists then it returns the profile of the User.
        - If the **usedId** provided by the **user(Id)** does not exist then a 404 error
        response is given.
      responses:
        "200": 
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/user"}
        "400":
          description: User not found
  /session/{Id}/{userId}/ban:
    parameters: 
      - $ref: "#/components/parameters/Id"
      - $ref: "#/components/parameters/userId"
    #* banUser
    post: 
      tags: ["User Ban actions"]
      summary: Ban an user.
      description: |-
        ## Information
        - If the **userId** provided by the **user(Id)** exists then banStatus is 
        changed from "None" to "Ban". 
        - If the **usedId** provided by the **user(Id)** does not exist then a 404 error
        response is given.
      operationId: banUser
      requestBody:
        content:
          application/json:
            schema: {$ref: "#/components/schemas/user"}
      responses:
        "200": 
          description: User banned successfully.
        "404":
          description: User not found.
    #* unbanUser
    put: 
      tags: ["User Ban actions"]
      summary: Unban an user.
      description: |-
        ## Information
        - If the **userId** provided by the **user(Id)** exists then banStatus is 
        changed from "Ban" to "None". 
        - If the **usedId** provided by the **user(Id)** does not exist then a 404 error
        response is given.
      operationId: banUser
      requestBody:
        content:
          application/json:
            schema: {$ref: "#/components/schemas/user"}
      responses:
        "200": 
          description: User Unbanned successfully.
        "404":
          description: User not found.
  /session/{Id}/{UserId}/follow:
    #* followUser
    post: 
      tags: ["User Follow actions"]
      summary: Follow an user.
      description: |-
        ## Information
        - If the **userId** provided by the **user(Id)** exists then followStatus is 
        changed from "None" to "Follow". 
        - If the **usedId** provided by the **user(Id)** does not exist then a 404 error
        response is given.
      operationId: followUser
      requestBody:
        content:
          application/json:
            schema: {$ref: "#/components/schemas/user"}
      responses:
        "200": 
          description: User followed successfully.
        "404":
          description: User not found.
    #* unfollowUser
    put: 
      tags: ["User Follow actions"]
      summary: Unfollow an user.
      description: |-
        ## Information
        - If the **userId** provided by the **user(Id)** exists then banStatus is 
        changed from "Follow" to "None". 
        - If the **usedId** provided by the **user(Id)** does not exist then a 404 error
        response is given.
      operationId: banUser
      requestBody:
        content:
          application/json:
            schema: {$ref: "#/components/schemas/user"}
      responses:
        "200": 
          description: User Unfollowed successfully.
        "404":
          description: User not found.
  /session/{Id}/{userId}/photo:
    parameters:
      - $ref : "#/components/parameters/Id"
      - $ref : "#/components/parameters/userId"
    #* uploadPhoto
    post: 
      tags: ["Photo actions"]
      summary: Upload a photo.
      description: |-
        # Information
        - If the **photo** provided has the right format then the photo is added.
        - If the **photo** provided does not have the right format then a 404 error response is given.
      operationId: uploadPhoto
      requestBody:
        content:
          image/*:
            schema: { $ref: "#/components/schemas/photo" }
      responses:
        "200":
          description: Photo uploaded successfully.
        "404":
          description: Image format is not correct.
  /session/{Id}/{userId}/photo/{photoId}:
    parameters:
      - $ref : "#/components/parameters/Id"
      - $ref : "#/components/parameters/userId"
      - $ref : "#/components/parameters/photoID"
    #* likePhoto
    post: 
      tags: ["Photo actions"]
      operationId: likePhoto
      summary: Like a photo.
      description: |-
        # Information
        - If the **photoId** provided exists then the like is added.
        - If the **usedId** provided does not exist then a 404 error response is given.
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/photo" }
      responses:
        "201":
          description: Like added successfully.
          content:
            application/json:
              schema: { $ref: "#/components/schemas/photo"}
        "404": {description: Photo not found.}
    #* unlikePhoto
    put: 
      tags: ["Photo actions"]
      operationId: unlikePhoto
      summary: Delete a like from a photo.
      description: |-
        # Information
        - If the **photoId** provided exists then the like is removed from the photo.
        - If the **photoId** provided does not exist then a 404 error response is given.
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/photo" }
      responses:
        "201":
          description: Like added successfully.
          content:
            application/json:
              schema: { $ref: "#/components/schemas/photo"}
        "404": {description: Photo not found.}
    #* deletePhoto 
    delete:
      tags: ["Photo actions"]
      operationId: deletePhoto
      summary: Remove a photo.
      description: |-
        # Information
        - If the **phototId** provided exists then the photo is removed.
        - If the **photoId** provided does not exist then a 404 error response is given.
      responses:
        "200": {description: Photo deleted successfully.}
        "404": {description: Photo not found}
  /session/{Id}/{userId}/photo/{photoId}/comment:
    parameters:
      - $ref : "#/components/parameters/Id"
      - $ref : "#/components/parameters/photoID"
      - $ref : "#/components/parameters/userId"
      - $ref: "#/components/parameters/commentID"
    #* commentPhoto
    post:
      tags: ["Comment actions"]
      summary: Add a comment under a Photo.
      description: |-
        # Information
        - If the **commentId** provided exists then the comment is added.
        - If the **usedId** provided does not exist then a 404 error response is given.
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/comment"}
      responses:
        "200":
          description:  Comment added successfully.
          content:
            application/json:
              schema: { $ref: "#/components/schemas/comment"}
        "404": {description: Comment not found.}
  /session/{Id}/{userId}/photo/{photoId}/comment/{commentId}:
    parameters:
      - $ref : "#/components/parameters/Id"
      - $ref : "#/components/parameters/userId"
      - $ref : "#/components/parameters/photoID"
      - $ref: "#/components/parameters/commentID"
    #* uncommentPhoto
    delete:
     operationId: uncommentPhoto
     tags: ["Comment actions"]
     summary: Remove a comment under a Photo.
     description: |-
        # Information
        - If the **commentId** provided exists then the comment is removed.
        - If the **usedId** provided does not exist then a 404 error response is given.
     responses:
       "200": {description: Comment removed successfully.}
       "404": {description: Comment not found.}
components:
  schemas:
    #* User schema
    user:
      title: User Schema
      description: This object represent a single User
      type: object
      properties:
        id:
          description: Unique user identifier
          type: integer
          readOnly: true
          example: user123
        username:
          description: User username
          type: string
          example: Maria Grey
        followStatus:
          description: Describe the follow status of the user
          type: string
          enum: ["Follow", "None"]
          example: None
        banStatus:
          description: Describe the ban status of the user
          type: string
          enum: ["Ban","None"]
          example: None
        followerStatus:
          description: Number of followers.
          type: integer
          readOnly: true
          example: 1420
        followingStatus:
          description: Number of followings.
          type: integer
          readOnly: true
          example: 820
        photoStatus:
          description: Number of photos published.
          type: integer
          readOnly: true
          example: 80
    #* Photo schema
    photo: 
      title: Photo Schema
      description: "This object represent a singe photo"
      type: object
      properties:
        id: 
          description:  Unique photo identifier
          type: string
          example: "#P1234"
          readOnly: true   
        likesCount:
          description: Number of likes.
          type: integer
          example: 15
          minimum: 0
          maximum : 9999999
        commentsCount:
          description: Number of comments.
          type: integer
          example: 20
          minimum: 0
          maximum : 9999999
        uploadDate:
          description: Upload date of a specific Photo.
          type: string
          example: "2022-11-02T09:00:00Z"
          readOnly: true
    #* Comment Schema
    comment: 
      title: Comment Schema
      description: This object represent a single comment
      type: object
      properties:
        id:
          description: Unique comment identifier
          type: string
          readOnly: true 
          example: "#C1234"
        content:
          description: Content of the comment
          type: string
          example: "Hello World!"
        uploadDate:
          description: Upload date of a specific Photo.
          type: string
          example: "2022-11-02T09:00:00Z"
          readOnly: true
  parameters:
    Id:
      schema:
        type: string
        example: "abcdef012345"
        readOnly: true
      name: Id
      in: path
      required: true
      description: "**ID** of the current user that is logged in WASAPhoto."
    userId:
      schema:
         type: string
         example: "abcdef012345"
      name: userId
      in: path
      required: true
      description: "**userID** that identifies a specific user of WASAPhoto."
    photoID:
      schema:
        type: integer
        example: 123456
        readOnly: true
      name: photoId 
      in: path
      required: true
      description: "**photoID** of a photo on a user profile."
    commentID:
      schema:
        type: integer
        example: 123456
        readOnly: true
      name: commentId
      in: path
      required: true
      description: "**commentID** of a single comment under a photo."